### ISSUE TITLE
New cop to detect test file name and test class inconsistencies

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#241]
Made this mistake today.

```ruby
# bad
# foo_test.rb
class BarTest ...

# good
# foo_test.rb
class FooTest ...
```

Besides the fact that this is confusing, it is possible to define the same class twice (via copy-paste from another file, for example), and the methods will be mixed/redefined at the end.

This cop should report if there is only one test class in the test file.

**Comment by andyw8** [comment]
I think this could be handled by the `ExpectMatchingDefinition` configuration option of `Naming/FileName`?

https://docs.rubocop.org/rubocop/cops_naming.html#namingfilename

**Comment by fatkodima** [comment]
Thanks! 
```yml
Naming/FileName:
  ExpectMatchingDefinition: true
  CheckDefinitionPathHierarchy: false
```

is what I was looking for.
